### ISSUE TITLE
Cannot include msgpack.h

### ISSUE THREAD

**Issue by sjoelund** [msgpack/msgpack-c#367] opened 2015-09-24 10:27 UTC
msgpack.h is full of references to bad #include directives. If I do:
```#include "/path/to/msgpack-c/include/msgpack.h"```, there is no `-I` flag that adds ```/path/to/msgpack-c/include/``` to the include path. This means the ```#include "msgpack/*.h"``` include directives in the other headers simply point to nowhere. They need to use either ```#include "../msgpack/*.h".```, or refer to the file directly ```#include "*.h".``` in order to work without makefile magic (I am developing for an application where I cannot be sure if the tool adds the include-directive or includes the file directly).

**Comment by redboltz** [comment] 2015-09-24 10:48
@sjoelund , msgpack-c requires to set include path to `path/to/msgpack-c/include`. I believe that it is a common way to implement libraries.

> They need to use either `#include "../msgpack/*.h"`., or refer to the file directly `#include "*.h"`.

I don't understand what does the above sentence mean. Is that a part of client codes?

**Comment by sjoelund** [comment] 2015-09-24 12:04
The most common way is to use relative include directives whenever possible because it makes it possible to directly include files directly from C-files. This also ensures that if there are two different includes with the same name, the one in the current directory has precedence.

As for the includes, the following works fine: https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/object.h#L21
But the following does not work: https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L21

**Comment by redboltz** [comment] 2015-09-24 12:49
@sjoelund , thank you for the clarification. I understand what the problem is. It is better that a client can use msgpack-c without adding an include path. And `#include <*.h>` style inclusion prevents that. If all header files that are located on msgpack-c/include are included using `#include "*.h"` style inclusion, the problem would fix. Some header files are from Boost. e.g. predef, See https://github.com/msgpack/msgpack-c/issues/300 and they are using `#include <*.h>` style. I need to add include style conversion process to CMakeLists.txt. I will fix the problem.

**Comment by redboltz** [comment] 2015-09-24 13:13
I didn't understand perfectly. If I want to fix the problem, I can't use relative path in natural way.

> They need to use either `#include "../msgpack/*.h"`., or refer to the file directly `#include "*.h"`. in order to work without makefile magic (I am developing for an application where I cannot be sure if the tool adds the include-directive or includes the file directly).

Now I understand the meaning of the sentence above. msgpack-c header files should be structured using sub directories. So I can't use `#include "*.h"` approach. `#include "../msgpack/*.h"` approach works well with sub directories. However, it is difficult to check how many "../" are required especially header files from Boost Libraries.

So I think that the effort to remove compiler option that adds include path is too much. Many libraries e.g. Boost.Libraries require to add the include path. I think that it is reasonable design decision.

That is my conclusion, so far.
Any ideas?

**Comment by sjoelund** [comment] 2015-09-24 13:15
For me, it would be sufficient if the C interface worked with relative paths (I assume the boost parts are only used for the C++ parts of msgpack-c).

**Comment by redboltz** [comment] 2015-09-24 13:23
> (I assume the boost parts are only used for the C++ parts of msgpack-c).
Unfortunately, it doesn't.
Maybe you mean https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L21. I can replace the line with `#include "msgpack/predef.h"`. However, predef.h is from Boost.Libraries even if it is a library for C. And it includes many header files. For example, https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/predef/other/endian.h
We need a portable way to check environment. See #300.

By the way, could you tell me why do you want to avoid to add include path flags to your compiler?

**Comment by sjoelund** [comment] 2015-09-24 14:13
Because in my case it is not standardized how Modelica tools handle the Modelica IncludeDirectory annotation (exactly how to include files). It works fine in the Modelica compiler I use, but might not in other compilers...

I could create a PR that converts include directives to relative pathnames. It simply uses:
```find msgpack -name "*.h" -exec ./b.sh {} ";"```
Where b.sh is:
```bash
#!/bin/bash

MSG=""
for d in `echo $1 | grep -o /`; do
  MSG="../$MSG"
done
sed -i s,"\\(# *include *\\)[<\"]\\(msgpack[/][A-Za-z0-9_-]*.*\\)[>\"]","\\1\"$MSG\\2\"", $1

DIRS=`echo $1 | tr "/" " "`
for d in $DIRS; do
  sed -i s,"\\(# *include *\"\\)\\(.*\\)[.][.]/$d/\\(.*\\)\"","\\1\\2\\3\"", $1
  MSG="../$MSG"
done
```

**Comment by redboltz** [comment] 2015-09-24 15:22
I've tested your script and it works perfectly :) However, understandability of the code is decreased. I can't accept to commit the modified codes to msgpack-c repository even though it removes include path restriction.  
It seems that the problem is Modelica compiler specific one. I don't know in detail about Modelica compiler. Does the compiler have default include path? If it is, creating symbolic links of msgpack-c on the default location. I guess that you've already thought about that...

There are many libraries that requires adding include path for example X11, http://www.opensource.apple.com/source/X11libs/X11libs-40/libXcursor/libXcursor-1.1.9/include/X11/Xcursor/Xcursor.h
I think that you need to apply the similar shell script to those kinds of libraries. 

So, I think that the script `b.sh` should be a part of your project that uses Modelica compiler. And you can add msgpack-c as a submodule of the project. And when msgpack-c is updated, your script is applied via some hook. 

I think that this is an appropriate approach in the case.

**Comment by redboltz** [comment] 2015-10-26 04:21
I will close the issue. If there are any problems, please let me know.

**Closed** 2015-11-21 13:37 UTC
