### ISSUE TITLE
a crash bug in MSGPACK_DEFINE_MAP

### ISSUE THREAD

**Issue by strrchr** [msgpack/msgpack-c#671] opened 2018-04-15 14:34 UTC
in include/msgpack/adaptor/detail/cpp11_define_map.hpp:
```C++
    void msgpack_unpack(msgpack::object const& o) const
    {
        if(o.type != msgpack::type::MAP) { throw msgpack::type_error(); }
        std::map<std::string, msgpack::object const*> kvmap;
        for (uint32_t i = 0; i < o.via.map.size; ++i) {
            kvmap.emplace(
                std::string(
                    o.via.map.ptr[i].key.via.str.ptr,
                    o.via.map.ptr[i].key.via.str.size),
                &o.via.map.ptr[i].val);
        }
        define_map_imp<std::tuple<Args&...>, sizeof...(Args)>::unpack(o, a, kvmap);
    }
```
We should check:
```C++
(o.via.map.ptr[i].key.type == msgpack::type::STR)
```

**Comment by redboltz** [comment] 2018-04-24 23:10
@strrchr , thank you for reporting the issue.
I will fix it. Also I need to check C++03 code-generation part.
Please wait a couple of days.

**Comment by redboltz** [comment] 2018-04-25 03:52
fixed and merged. If the problem is not fixed, please reopen the issue.

**Closed** 2018-04-25 03:52 UTC
