### ISSUE TITLE
MSGPACK_ENABLE_GCC_CXX_ATOMIC - Failed

### ISSUE THREAD

**Issue by wfjm** [msgpack/msgpack-c#905] opened 2020-07-31 17:34 UTC
When running `cmake` on the `cpp_master` branch on Ubuntu 18.04  I get a
```
    -- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC
    -- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC - Failed
```

The test code in `CMakeLists.txt` reads
``` c++
#include <bits/atomicity.h>
int atomic_sub(int i) { return __gnu_cxx::__exchange_and_add(&i, -1) - 1; }
int atomic_add(int i) { return __gnu_cxx::__exchange_and_add(&i, 1) + 1; }
int main(int argc, char * argv[])
{
    atomic_sub(1);
    atomic_add(1);
}
```

The culprit is that since quite some time the header is under
```
#include <ext/atomicity.h>
```

Looking through some old systems is see that
- up to gcc 4.1.1 I find `bits/atomicity.h`
- after gcc 4.6.3 I find `ext/atomicity.h`

so the transition was somewhere between gcc 4.1.1 and 4.6.3. Ubuntu 18.04 has `gcc version 7.5.0`

The code compiles and tests without `atomicity.h`, hard to judge whether there are performance impacts.
In case atomic actions are important, it seems to me that `std::atomic` is the natural choice these days.

In closing the steps to reproduce (on an Ubuntu 18.04 system, likely on all current Ubuntu/Debian systems):
```
  git clone https://github.com/msgpack/msgpack-c.git
  cd msgpack-c
  git checkout cpp_master 
  git checkout 70912ff

  mkdir build
  cd build
  cmake -DMSGPACK_CXX17=ON ..
```

**Comment by redboltz** [comment] 2020-07-31 23:58
> In case atomic actions are important, it seems to me that std::atomic is the natural choice these days.

Yes. since C++11, msgpack-c uses `std::atomic`.
See
https://github.com/msgpack/msgpack-c/blob/6598c6228fb9ce798a7bc1e6300cc8af514af0a7/include/msgpack/v1/unpack.hpp#L257-L264

For C++03,  msgpack-c provides `_msgpack_sync_incr_and_fetch`. It is not a standard way so there are various compiler support. 

https://github.com/msgpack/msgpack-c/blob/6598c6228fb9ce798a7bc1e6300cc8af514af0a7/include/msgpack/sysdep.hpp#L44-L69

https://github.com/msgpack/msgpack-c/blob/6598c6228fb9ce798a7bc1e6300cc8af514af0a7/include/msgpack/gcc_atomic.hpp
is only for older compilers.

However the top level CMakeLists.txt always check it. And outputs `Failed` message.
I think that cmake process itself is successfully finished even if `Failed` is output.

Is that right ?

If it is, the problem is not so critical but msgpack-c shouldn't output misleading message at the cmake process.
I will investigate it.

**Comment by redboltz** [comment] 2020-08-01 08:58
#906 should fix the issue.

**Comment by redboltz** [comment] 2020-08-07 01:31
#906 merged.

**Closed by redboltz** 2020-08-07 01:31 UTC
