### ISSUE TITLE
Compile errors when using MSGPACK_DEFINE in std::vector with a packed struct in Visual Studio 2015

### ISSUE THREAD

**Issue by reza-ebrahimi** [msgpack/msgpack-c#477] opened 2016-06-05 17:51 UTC
The picture descibes problem:

![untitled](https://cloud.githubusercontent.com/assets/11276982/15807176/0b4a6232-2b6c-11e6-8441-12b41e1c5a70.png)

**Comment by reza-ebrahimi** [comment] 2016-06-05 18:19
I found the problem:

problem is when using ```std::vector``` with ```MSGPACK_DEFINE```.

    typedef struct MessageUpdate
    {
	    QString archive;
	    std::vector<QString> items;

	    MSGPACK_DEFINE(archive, items)
    };

**Comment by redboltz** [comment] 2016-06-05 23:01
msgpack-c doesn't contain the adaptor for QString. So you need to write the adaptor for QString.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#non-intrusive-approach

```C++

// Insert adaptor for QString here

typedef struct test1
{
    std::vector<QString> item;
    MSGPACK_DEFINE(item)
};

typedef struct test2
{
    QString item;
    std::vector<test1> items;

    MSGPACK_DEFINE(item, items)
};
```

**Comment by redboltz** [comment] 2016-06-06 00:00
To implement QString adaptor, you can refer to std::string adaptor implementation. https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/adaptor/string.hpp#L26

There is an alternative approach. Remove Qt objects from the core of the code, using them to just interfaces of Qt library. If you replace QString with std::string, your code works as you expected. See
http://melpon.org/wandbox/permlink/cRTfD6345wxnV6ek
(I removed C-Style typedef)

**Comment by reza-ebrahimi** [comment] 2016-06-06 02:25
@redboltz I wrote an adapter for ```QString```, I forget to mention that in previous posts, that was not the problem, if you put ```std::string``` compile errors still happens.

**Comment by redboltz** [comment] 2016-06-06 02:30
> @redboltz I wrote an adapter for QString, I forget to mention that in previous posts, that was not the problem, 

Ok, you wrote an adaptor.

> if you put std::string compile errors still happens.

I believe that the following code makes no errors on your environment:
http://melpon.org/wandbox/permlink/cRTfD6345wxnV6ek

Is that right?

**Comment by redboltz** [comment] 2016-06-06 04:35
@reza-ebrahimi , I don't know why but your post seems to be deleted. 

Let's confirm the current situation.

1. You wrote the adaptor for QString and It works as you expected.
2. You wrote MSGPACK_DEFINE with std::vector<QString>, it makes an error.
3. I wrote a small program that uses std::string instead of QString. It works fine. (At least on my environment)

I think that if 3 works correctly, it indicates that the adaptor for std::vector works well. If the following `test3` works well, it indicates that your adaptor works well.

```C++
struct test3
{
    QString item;
    MSGPACK_DEFINE(item);
};
```

So the problem is caused by the combination of QString and std::vector. It is pretty hard to check. The next step is checking `pack`, `unpack`, `convert`, and `as` separately.

```C++
// test for packing
test2 t2;
std::stringstream ss;
msgpack::pack(ss, t2);
```

Check compile error this point. If no compile errors found, then

```C++
// test for packing
test2 t2;
std::stringstream ss;
msgpack::pack(ss, t2);

auto oh = msgpack::unpack(ss.str().data(), ss.str().size());
auto obj = oh.get();
```

Check compile error this point. If no compile errors found, then

```C++
// test for packing
test2 t2;
std::stringstream ss;
msgpack::pack(ss, t2);

auto oh = msgpack::unpack(ss.str().data(), ss.str().size());
auto obj = oh.get();

test2 tt2;
obj.convert(tt2);

```

Check compile error this point. If no compile errors found, then

```C++
// test for packing
test2 t2;
std::stringstream ss;
msgpack::pack(ss, t2);

auto oh = msgpack::unpack(ss.str().data(), ss.str().size());
auto obj = oh.get();

test2 tt2;
obj.convert(tt2);

obj.as<test2>();
```

Check compile error this point.

I think that the results of above checking process are helpful to solve the issue.

**Comment by reza-ebrahimi** [comment] 2016-06-06 13:51
@redboltz The problem is ```clr``` compiler option, my project uses some .Net assemblies and configured with ```Common Language Runtime Support (/clr)``` compile option, but that works well in Visual Studio 2012 compiler and have errors in 2015, it may related to ```c++11``` compiler options and ```template```s.

**Comment by reza-ebrahimi** [comment] 2016-06-07 05:05
@redboltz have you checked it? Thanks a lot for your effort.

**Comment by redboltz** [comment] 2016-06-07 23:19
@reza-ebrahimi , I'm digging the problem. I reproduced the same errors with `/clr`option.
 It seems that MSVC's problem. And microsoft provides a solition.

Could you test http://melpon.org/wandbox/permlink/nj2JDIhILc4LC7lR on your environment?
Maybe you would get error.

If you enable `/clr`, the keyword `nullptr` is regard to managed code. That's why `nullptr` cannot convert to `...`. It should be comple on ISO C++11.
See
https://msdn.microsoft.com/en-us/library/4ex65770.aspx

The solution is using `__nullptr` instead of `nullptr`. I'm not sure when and where?
We need to use `__nullptr` only MSVC, only from the specific version.
In addition, msgpack-c is a header-only library. If I insert something like `#define nullptr __nullptr`, all codes that include `msgpack.hpp` is affected. The code might expect `nullptr` is managed one.

I considered other option. That is introducing `msgpack_nullptr`. And controls definition of that conditionally. But I think that it is too much only for MSVC /clr option.

I don't find an appropriate approach yet.

For your project, you can replace `nullptr` with `__nullptr` on the part of code you got compile errors. I believe that it could be a temporary solution for you.

**Comment by redboltz** [comment] 2016-06-09 23:48
@reza-ebrahimi , I post the PR to fix the issue. Try #481.

Here is the instruction to get the PR branch:

```
git checkout -b redboltz-support_msvc_cli master
git pull https://github.com/redboltz/msgpack-c.git support_msvc_cli
```

The compile errors should be solved.

I got some warnings something like `The code compiled as native code.` at `_msgpack_store16`, but I'm not sure that is a problem or not. At least, all tests are passed.

After you test it on your environment, I will merge the PR.

**Comment by reza-ebrahimi** [comment] 2016-06-12 20:36
@redboltz Ok, Thanks a lot, I'll test it and report the result.

**Comment by redboltz** [comment] 2016-06-13 10:15
@reza-ebrahimi ,thank you. I look forward to your report :)

**Comment by reza-ebrahimi** [comment] 2016-06-17 07:08
@redboltz Congratulations, The compile errors disappeared!
Thanks for your effort, when you commit these changes to master branch?

**Comment by redboltz** [comment] 2016-06-18 23:13
Just merged.

**Closed by redboltz** 2016-06-18 23:13 UTC
