### ISSUE TITLE
3.1.0 test failure on s390x

### ISSUE THREAD

**Issue by ueno** [msgpack/msgpack-c#724] opened 2018-08-22 15:17 UTC
I got the following failure when building 3.1.0 on s390x:
```
[ RUN      ] MSGPACKC.simple_buffer_timestamp_32
/builddir/build/BUILD/msgpack-3.1.0/test/msgpack_c.cpp:656: Failure
      Expected: ts.tv_sec
      Which is: 4294967295
To be equal to: ts2.tv_sec
      Which is: -3949359184
[  FAILED  ] MSGPACKC.simple_buffer_timestamp_32 (0 ms)
```
The full log is available from:
https://koji.fedoraproject.org/koji/taskinfo?taskID=29228752

**Comment by ueno** [comment] 2018-08-24 15:56
Interestingly, the unpacked value is unpredictable.  In a new build I got:
```
[ RUN      ] MSGPACKC.simple_buffer_timestamp_32
/builddir/build/BUILD/msgpack-3.1.0/test/msgpack_c.cpp:656: Failure
      Expected: ts.tv_sec
      Which is: 4294967295
To be equal to: ts2.tv_sec
      Which is: -3307475024
[  FAILED  ] MSGPACKC.simple_buffer_timestamp_32 (0 ms)
```

**Comment by redboltz** [comment] 2018-08-26 02:13
Thank you for reporting the issue. The issue is not reproduced on my environment.
But I updated the code. It might fix the issue.
Could you test #726?

**Comment by ueno** [comment] 2018-08-27 10:13
Thank you, but I am afraid it didn't help. However, looking at the surrounded code, I noticed a potential truncation of an int64_t value. So modifying it like this works:
```
diff --git a/include/msgpack/timestamp.h b/include/msgpack/timestamp.h
index 4d7df83d..50aa698e 100644
--- a/include/msgpack/timestamp.h
+++ b/include/msgpack/timestamp.h
@@ -28,7 +28,9 @@ static inline bool msgpack_object_to_timestamp(const msgpack_object* obj, msgpac
     switch (obj->via.ext.size) {
     case 4:
         ts->tv_nsec = 0;
-        _msgpack_load32(uint32_t, obj->via.ext.ptr, &ts->tv_sec);
+        uint32_t v;
+        _msgpack_load32(uint32_t, obj->via.ext.ptr, &v);
+        ts->tv_sec = v;
         return true;
     case 8: {
         uint64_t value;
```

**Comment by redboltz** [comment] 2018-08-27 14:48
Thank you!
I got confused 32/64/96 bit branch and was looking for the wrong place.

I will (force )update #726 based on your fix.

**Comment by redboltz** [comment] 2018-08-27 15:14
Merged. If you still have the problem, please reopen it.

**Closed** 2018-08-27 15:13 UTC
